hostname: 'Leaf-15'

routing:
  ipv4_multi: 'yes'

interfaces:

  Loopback0:
    name: 'Routing Loopback'
    ip_address: '172.16.255.15'
    subnet_mask: '255.255.255.255'
    loopback: 'yes'
    pim_enable: 'no'

  Loopback1:
    name: 'NVE Loopback'
    ip_address: '172.16.254.15'
    subnet_mask: '255.255.255.255'
    loopback: 'yes'
    pim_enable: 'yes'

  GigabitEthernet1/0/1:
    name: 'Backbone interface to Spine-03'
    ip_address: '172.16.15.15'
    subnet_mask: '255.255.255.0'
    loopback: 'no'
    pim_enable: 'yes'

  GigabitEthernet1/0/2:
    name: 'Backbone interface to Spine-04'
    ip_address: '172.16.25.15'
    subnet_mask: '255.255.255.0'
    loopback: 'no'
    pim_enable: 'yes'  

ospf:
  router_id: '172.16.255.15'

pim:
  rp_address: '172.16.255.255'

bgp:
  as_number: '65001'
  router_id: 'Loopback0'
  neighbors:
    '172.16.255.3':
     peer_as_number: '65001'
     source_interface: 'Loopback0'

    '172.16.255.4':
     peer_as_number: '65001'
     source_interface: 'Loopback0'

#layer 3 interface
overlay_interfaces:
  Loopback11:
    name: 'Vrf Loopback'
    ip_address: '10.15.11.11'
    subnet_mask: '255.255.255.0'
    loopback: 'yes'
    vrf: 'green'

  Loopback12:
    name: 'Vrf Loopback'
    ip_address: '10.15.12.12'
    subnet_mask: '255.255.255.0'
    loopback: 'yes'
    vrf: 'blue'
